"""Initial database schema

Revision ID: d11ae4a6a0ae
Revises: 
Create Date: 2025-07-26 03:10:01.914500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11ae4a6a0ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genre')
    op.drop_table('credit')
    op.drop_table('movie_ids')
    op.drop_table('genre')
    op.drop_table('people')
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_adult', sa.BOOLEAN(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('original_title', sa.VARCHAR(), nullable=True),
    sa.Column('overview', sa.TEXT(), nullable=True),
    sa.Column('poster_path', sa.VARCHAR(), nullable=True),
    sa.Column('release_date', sa.VARCHAR(), nullable=True),
    sa.Column('runtime', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('vote_average', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_adult', sa.BOOLEAN(), nullable=True),
    sa.Column('alias', sa.TEXT(), nullable=True),
    sa.Column('biography', sa.TEXT(), nullable=True),
    sa.Column('birthday', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(), nullable=True),
    sa.Column('profile_path', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_ids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('character_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_genre',
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.Column('movie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'movie_id')
    )
    # ### end Alembic commands ###
